# Generated by Django 3.1.1 on 2020-10-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regelhulpify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='log_date',
        ),
    ]
