# Generated by Django 3.1.1 on 2020-10-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regelhulpify', '0002_remove_tool_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='expl',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='tool',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='regelhulpify.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='expl',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
