# Generated by Django 3.1.1 on 2020-10-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regelhulpify', '0003_auto_20201008_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='nextquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comesfrom', to='regelhulpify.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='resulttext',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('tool', 'position'), name='unique position within tool'),
        ),
    ]
