# Generated by Django 3.1.1 on 2020-10-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regelhulpify', '0004_auto_20201011_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resultaat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(),
        ),
    ]
