# Generated by Django 3.1.1 on 2020-10-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regelhulpify', '0005_auto_20201013_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='resultaat',
            new_name='result',
        ),
    ]
