# Generated by Django 3.1.1 on 2020-10-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regelhulpify', '0008_auto_20201014_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='img',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
