# Generated by Django 3.1.1 on 2020-10-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regelhulpify', '0009_tool_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='img',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
