# Generated by Django 3.1.1 on 2020-11-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regelhulpify', '0009_tool_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='img',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
